### ISSUE TITLE
I used it but nothing happened. Is the method I used wrong?

### ISSUE THREAD

**Issue by Stowaway-y** [mirfansulaiman/CustomHeader#1]
I used it but nothing happened. Is the method I used wrong?

**Comment by mirfansulaiman** [comment]
> I used it but nothing happened. Is the method I used wrong?

Have you choose the HTTP method button and click the save button before using it? 

![Screen Shot 2019-11-17 at 17 07 56](https://user-images.githubusercontent.com/6317984/69006079-dac1da00-095c-11ea-837f-2f6cdf0bf1b0.png)

**Comment by Stowaway-y** [comment]
I understand it wrong.I found it on the log++, but I thought it would be added in the proxy,
sorry

**Comment by serfend** [comment]
+1,it seems not work, even though i'd click `all methods` and `save`

**Comment by mirfansulaiman** [comment]
> +1,it seems not work, even though i'd click `all methods` and `save`

Hi, what burp version do you use?

**Comment by serfend** [comment]
> > +1,it seems not work, even though i'd click `all methods` and `save`
> 
> Hi, what burp version do you use?

version `2020.2`,i'm supposed to update it i guess
