### ISSUE TITLE
Header not visible in stream

### ISSUE THREAD

**Issue by log2-industrialist** [mirfansulaiman/CustomHeader#2]
Hi,
I have a short question and maybe I am doing something wrong: 
Maybe you can be so kind to give me a quick answer. I know that you are certainly very busy
I added the header extension to burpsuite
I added the header in the session, I need to set two X-headers. 
But I can't seem to see the headers in the burpsuite flow of posts. 
I apologize for all inconvenience and 
with many Thanks and regards
H.

**Comment by mirfansulaiman** [comment]
Hi @log2-industrialist , 

What is burp version do you use?

**Comment by log2-industrialist** [comment]
Hi Irfan,
thanks for the quick replay.
I use Burpsuite Professional 2021.3.3 (The latest)
Thanks and regards
Jolger

Von: Irfan Sulaiman ***@***.***>
Gesendet: Dienstag, 20. April 2021 09:42
An: mirfansulaiman/CustomHeader ***@***.***>
Cc: ***@***.***; Mention ***@***.***>
Betreff: Re: [mirfansulaiman/CustomHeader] Header not visible in stream (#2)


Hi @log2-industrialist<https://github.com/log2-industrialist> ,

What is burp version do you use?

**Comment by mirfansulaiman** [comment]
I already check the extension within the Burp version 2021.3.3 (The latest) and the extension is working as well. 
Just a reminder, don't forget to choose HTTP Method Option and click the "save" button after adding a custom header.

![image](https://user-images.githubusercontent.com/6317984/115358972-67269b00-a1e8-11eb-8f40-d133e76ac327.png)

The picture below shows the custom header is already including on Request. 

![image](https://user-images.githubusercontent.com/6317984/115359130-9210ef00-a1e8-11eb-9f7d-7075aa91408f.png)

please let me know if you still facing the problem ya.

**Comment by log2-industrialist** [comment]
Hi Iran, 
thanks for your effort , I am going to check .

**Comment by log2-industrialist** [comment]
I could only see it in the session tracer in "Project Options->Session Handling Rules", after the rule is applied. 
The header is not visible in the usual lists like ( Target->Sitemaps ). But it seems to be transmitted, so that is ok.
Again, thanks for all your help.

**Comment by mirfansulaiman** [comment]
Yap, this extension does not appear in Burp History or Sitemap. But, you can use [Burpsuite Flow Extender](https://portswigger.net/bappstore/ee1c45f4cc084304b2af4b7e92c0a49d) to see all modified request from Burp Extention.
